Add beta client for ServiceProvider and related workflow
sherweb/Public-Apis pull request #15
Opened 2021-04-21 14:51 UTC by jimbeaudoin

2021-04-21 14:59 UTC, jimbeaudoin commented on NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider/Sherweb.Apis.ServiceProvider.csproj
> +    <PackageReference Include="Azure.Core" Version="1.13.0" />
The client does not seem to be like the Distributor client. The dependencies are not the same. I don't know why but I think maybe we are using a newer autorest and it is now using Microsoft.Azure.AutoRest.CSharp instead of Microsoft.Rest.ClientRuntime?

2021-04-22 13:27 UTC, sw-spons commented on NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider/Sherweb.Apis.ServiceProvider.csproj
> +    <PackageReference Include="Azure.Core" Version="1.13.0" />
That looks really weird, given the "-beta" of the nuget. I'll look into that

2021-04-22 13:45 UTC, sw-spons commented on NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider/Sherweb.Apis.ServiceProvider.csproj
> +    <PackageReference Include="Azure.Core" Version="1.13.0" />
So, I fixed it, you can see details on Teams. Call me if you have any question.

2021-04-22 13:46 UTC, sw-spons commented on NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider/Sherweb.Apis.ServiceProvider.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Please add the Factory to create the client, just like I did for Distributor Client

2021-04-22 13:46 UTC, sw-spons reviewed
Missing the factory, and client generated is not correct, details on Teams. :)

2021-04-22 16:25 UTC, jimbeaudoin commented on NugetPackagesSourceCode/Sherweb.Apis.ServiceProvider/Sherweb.Apis.ServiceProvider.csproj
> +    <PackageReference Include="Azure.Core" Version="1.13.0" />
It should be fixed now.

2021-04-22 17:01 UTC, sw-spons requested changes

2021-04-22 17:01 UTC, sw-spons commented on .github/workflows/beta.yml
> +  ServiceProvider:
Je le mettrais avant SampleCode pour plus de lisibilité mais c'est toi qui vois

2021-04-22 17:36 UTC, jimbeaudoin commented on .github/workflows/beta.yml
> +  ServiceProvider:
Bonne idée

2021-04-22 17:42 UTC, sw-spons approved these changes

2021-04-22 17:43 UTC, merged