Add Postman files, restructure files tree, edit readme
sherweb/Public-Apis pull request #6
Opened 2020-12-01 20:19 UTC by sw-spons

2020-12-04 18:39 UTC, dgauthier1 requested changes

2020-12-04 18:39 UTC, dgauthier1 commented on .github/workflows/master.yml
> +      working-directory: ./SourceCode/Sherweb.Apis.Authorization
Je parlerais des nugets, donc NugetsSourceCode

2020-12-04 18:39 UTC, dgauthier1 commented on .github/workflows/master.yml
> +      working-directory: ./SourceCode/Sherweb.Apis.Distributor
Je parlerais des nugets, donc NugetsSourceCode

2020-12-04 18:39 UTC, dgauthier1 commented on .github/workflows/pullrequests.yml
> +      working-directory: ./SourceCode/Sherweb.Apis.Authorization
Je parlerais des nugets, donc NugetsSourceCode

2020-12-04 18:39 UTC, dgauthier1 commented on .github/workflows/pullrequests.yml
> +      working-directory: ./SourceCode/Sherweb.Apis.Distributor
Je parlerais des nugets, donc NugetsSourceCode

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
>  ![Fenêtres pour copier toutes les informations nécessaires afin de se connecter aux API](docs/FR_ApiInformations.png)
enlever le fameux bouton mauve comme suggéré dans la démo

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
1 - Chaque dossier sous **SourceCode** -> NugetsSourceCode.

2 - je ne comprends pas ce que veux dire "Pour générer un code, vous devez ouvrir le fichier .sln dans Visual Studio."... Pour utiliser le code? Pour hmmm...

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Dans le dossier « SampleCode », vous pouvez trouver tous les exemples démontrant comment utiliser les paquets NuGet. Tous les exemples sont en langage C#. C'est là que vous aurez besoin de l'identifi
En haut le dossier est **SourceCode** tandis que là il est entre guillements, mettre tous pareil quand on parle de dossiers

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Dans le dossier « Postman », vous pouvez trouver les fichiers permettant de tester les APIs avec [Postman](https://www.postman.com/). Il y a une "Collection" pour chaque API plus un "Environement". V
En haut le dossier est **SourceCode** tandis que là il est entre guillements, mettre tous pareil quand on parle de dossiers

2020-12-04 18:39 UTC, dgauthier1 commented on .github/workflows/master.yml
> +      working-directory: ./SourceCode/Sherweb.Apis.Authorization
Plus bas on parle de Nuget packages, donc voir si on veut mettre NugetPackagesSourceCode

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
Je viens de voir qu'en bas on parlait de build. Je suppose que c'est générer?... voici donc mes suggestions poru le français si il n'y a pas mieux que générer : Utilisez le fichier .sln pour ouvrir le code dans Visual Studio.

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
Et dans le pire des cas, si on utilise quan dmême générer, je dirais Pour générer le code,...

2020-12-04 18:39 UTC, dgauthier1 commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
3 - Tout le code source des paquets

2020-12-04 18:41 UTC, sw-spons commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
On pourrait aussi juste enlever cette phrase que je trouve inutile, non ?

2020-12-07 15:43 UTC, dgauthier1 commented on LISEZMOI.md
> +Nous avons une organisation chez NuGet (https://www.nuget.org/profiles/Sherweb). Tous les paquets NuGet publics s'y trouvent. Ce dépôt présente tous les codes sources des paquets, si vous voulez les
3 - tous les codes sources des paquets -> tout le code source des paquets?

2020-12-07 16:23 UTC, dgauthier1 approved these changes

2020-12-07 16:24 UTC, dgauthier1 approved these changes
Approved

2020-12-07 16:28 UTC, merged